// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/direct_flutter_api.dart';
import 'api/ffmpeg_flutter_api.dart';
import 'api/flutter_api.dart';
import 'api/iroh_live_flutter_api.dart';
import 'api/live_flutter_api.dart';
import 'api/moq_flutter_api.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw);

  @protected
  Map<String, bool> dco_decode_Map_String_bool_None(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  FlutterAudioSamples dco_decode_box_autoadd_flutter_audio_samples(dynamic raw);

  @protected
  FlutterBroadcastCatalog dco_decode_box_autoadd_flutter_broadcast_catalog(
    dynamic raw,
  );

  @protected
  FlutterCatalog dco_decode_box_autoadd_flutter_catalog(dynamic raw);

  @protected
  FlutterConnectionStats dco_decode_box_autoadd_flutter_connection_stats(
    dynamic raw,
  );

  @protected
  FlutterFilterType dco_decode_box_autoadd_flutter_filter_type(dynamic raw);

  @protected
  FlutterMoqObject dco_decode_box_autoadd_flutter_moq_object(dynamic raw);

  @protected
  FlutterNamespaceAnnouncement
  dco_decode_box_autoadd_flutter_namespace_announcement(dynamic raw);

  @protected
  FlutterPublisherStatus dco_decode_box_autoadd_flutter_publisher_status(
    dynamic raw,
  );

  @protected
  FlutterSubscriberStatus dco_decode_box_autoadd_flutter_subscriber_status(
    dynamic raw,
  );

  @protected
  FlutterTicketInfo dco_decode_box_autoadd_flutter_ticket_info(dynamic raw);

  @protected
  FlutterVideoFrame dco_decode_box_autoadd_flutter_video_frame(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_8(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FlutterAudioCodec dco_decode_flutter_audio_codec(dynamic raw);

  @protected
  FlutterAudioRendition dco_decode_flutter_audio_rendition(dynamic raw);

  @protected
  FlutterAudioSamples dco_decode_flutter_audio_samples(dynamic raw);

  @protected
  FlutterBroadcastCatalog dco_decode_flutter_broadcast_catalog(dynamic raw);

  @protected
  FlutterCaptureDevice dco_decode_flutter_capture_device(dynamic raw);

  @protected
  FlutterCatalog dco_decode_flutter_catalog(dynamic raw);

  @protected
  FlutterConnectionStats dco_decode_flutter_connection_stats(dynamic raw);

  @protected
  FlutterDecodedAudioFrame dco_decode_flutter_decoded_audio_frame(dynamic raw);

  @protected
  FlutterDecodedVideoFrame dco_decode_flutter_decoded_video_frame(dynamic raw);

  @protected
  FlutterDirectEvent dco_decode_flutter_direct_event(dynamic raw);

  @protected
  FlutterEncodedAudioFrame dco_decode_flutter_encoded_audio_frame(dynamic raw);

  @protected
  FlutterEncodedVideoFrame dco_decode_flutter_encoded_video_frame(dynamic raw);

  @protected
  FlutterEncoderPreset dco_decode_flutter_encoder_preset(dynamic raw);

  @protected
  FlutterFilterType dco_decode_flutter_filter_type(dynamic raw);

  @protected
  FlutterGroupOrder dco_decode_flutter_group_order(dynamic raw);

  @protected
  FlutterHardwareAccel dco_decode_flutter_hardware_accel(dynamic raw);

  @protected
  FlutterLiveEvent dco_decode_flutter_live_event(dynamic raw);

  @protected
  FlutterMoqObject dco_decode_flutter_moq_object(dynamic raw);

  @protected
  FlutterMoqStats dco_decode_flutter_moq_stats(dynamic raw);

  @protected
  FlutterNamespaceAnnouncement dco_decode_flutter_namespace_announcement(
    dynamic raw,
  );

  @protected
  FlutterObjectStatus dco_decode_flutter_object_status(dynamic raw);

  @protected
  FlutterPublisherStatus dco_decode_flutter_publisher_status(dynamic raw);

  @protected
  FlutterStreamEvent dco_decode_flutter_stream_event(dynamic raw);

  @protected
  FlutterSubscriberStatus dco_decode_flutter_subscriber_status(dynamic raw);

  @protected
  FlutterTicketInfo dco_decode_flutter_ticket_info(dynamic raw);

  @protected
  FlutterTrackInfo dco_decode_flutter_track_info(dynamic raw);

  @protected
  FlutterTrackStatus dco_decode_flutter_track_status(dynamic raw);

  @protected
  FlutterTrackStatusCode dco_decode_flutter_track_status_code(dynamic raw);

  @protected
  FlutterVideoCodec dco_decode_flutter_video_codec(dynamic raw);

  @protected
  FlutterVideoFrame dco_decode_flutter_video_frame(dynamic raw);

  @protected
  FlutterVideoQuality dco_decode_flutter_video_quality(dynamic raw);

  @protected
  FlutterVideoQualityFfmpeg dco_decode_flutter_video_quality_ffmpeg(
    dynamic raw,
  );

  @protected
  FlutterVideoRendition dco_decode_flutter_video_rendition(dynamic raw);

  @protected
  FlutterVideoTrack dco_decode_flutter_video_track(dynamic raw);

  @protected
  int dco_decode_i_16(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<FlutterAudioRendition> dco_decode_list_flutter_audio_rendition(
    dynamic raw,
  );

  @protected
  List<FlutterCaptureDevice> dco_decode_list_flutter_capture_device(
    dynamic raw,
  );

  @protected
  List<FlutterDirectEvent> dco_decode_list_flutter_direct_event(dynamic raw);

  @protected
  List<FlutterEncodedVideoFrame> dco_decode_list_flutter_encoded_video_frame(
    dynamic raw,
  );

  @protected
  List<FlutterLiveEvent> dco_decode_list_flutter_live_event(dynamic raw);

  @protected
  List<FlutterMoqObject> dco_decode_list_flutter_moq_object(dynamic raw);

  @protected
  List<FlutterNamespaceAnnouncement>
  dco_decode_list_flutter_namespace_announcement(dynamic raw);

  @protected
  List<FlutterStreamEvent> dco_decode_list_flutter_stream_event(dynamic raw);

  @protected
  List<FlutterTrackInfo> dco_decode_list_flutter_track_info(dynamic raw);

  @protected
  List<FlutterVideoQuality> dco_decode_list_flutter_video_quality(dynamic raw);

  @protected
  List<FlutterVideoRendition> dco_decode_list_flutter_video_rendition(
    dynamic raw,
  );

  @protected
  List<FlutterVideoTrack> dco_decode_list_flutter_video_track(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_i_16_loose(dynamic raw);

  @protected
  Int16List dco_decode_list_prim_i_16_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, bool)> dco_decode_list_record_string_bool(dynamic raw);

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  FlutterMoqObject? dco_decode_opt_box_autoadd_flutter_moq_object(dynamic raw);

  @protected
  FlutterNamespaceAnnouncement?
  dco_decode_opt_box_autoadd_flutter_namespace_announcement(dynamic raw);

  @protected
  FlutterPublisherStatus? dco_decode_opt_box_autoadd_flutter_publisher_status(
    dynamic raw,
  );

  @protected
  FlutterSubscriberStatus? dco_decode_opt_box_autoadd_flutter_subscriber_status(
    dynamic raw,
  );

  @protected
  FlutterTicketInfo? dco_decode_opt_box_autoadd_flutter_ticket_info(
    dynamic raw,
  );

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_8(dynamic raw);

  @protected
  Quality dco_decode_quality(dynamic raw);

  @protected
  QualityConstraints dco_decode_quality_constraints(dynamic raw);

  @protected
  (String, bool) dco_decode_record_string_bool(dynamic raw);

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  (int, int) dco_decode_record_u_32_u_32(dynamic raw);

  @protected
  (int, int, int) dco_decode_record_u_8_u_8_u_8(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  Map<String, String> sse_decode_Map_String_String_None(
    SseDeserializer deserializer,
  );

  @protected
  Map<String, bool> sse_decode_Map_String_bool_None(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  FlutterAudioSamples sse_decode_box_autoadd_flutter_audio_samples(
    SseDeserializer deserializer,
  );

  @protected
  FlutterBroadcastCatalog sse_decode_box_autoadd_flutter_broadcast_catalog(
    SseDeserializer deserializer,
  );

  @protected
  FlutterCatalog sse_decode_box_autoadd_flutter_catalog(
    SseDeserializer deserializer,
  );

  @protected
  FlutterConnectionStats sse_decode_box_autoadd_flutter_connection_stats(
    SseDeserializer deserializer,
  );

  @protected
  FlutterFilterType sse_decode_box_autoadd_flutter_filter_type(
    SseDeserializer deserializer,
  );

  @protected
  FlutterMoqObject sse_decode_box_autoadd_flutter_moq_object(
    SseDeserializer deserializer,
  );

  @protected
  FlutterNamespaceAnnouncement
  sse_decode_box_autoadd_flutter_namespace_announcement(
    SseDeserializer deserializer,
  );

  @protected
  FlutterPublisherStatus sse_decode_box_autoadd_flutter_publisher_status(
    SseDeserializer deserializer,
  );

  @protected
  FlutterSubscriberStatus sse_decode_box_autoadd_flutter_subscriber_status(
    SseDeserializer deserializer,
  );

  @protected
  FlutterTicketInfo sse_decode_box_autoadd_flutter_ticket_info(
    SseDeserializer deserializer,
  );

  @protected
  FlutterVideoFrame sse_decode_box_autoadd_flutter_video_frame(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_8(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FlutterAudioCodec sse_decode_flutter_audio_codec(
    SseDeserializer deserializer,
  );

  @protected
  FlutterAudioRendition sse_decode_flutter_audio_rendition(
    SseDeserializer deserializer,
  );

  @protected
  FlutterAudioSamples sse_decode_flutter_audio_samples(
    SseDeserializer deserializer,
  );

  @protected
  FlutterBroadcastCatalog sse_decode_flutter_broadcast_catalog(
    SseDeserializer deserializer,
  );

  @protected
  FlutterCaptureDevice sse_decode_flutter_capture_device(
    SseDeserializer deserializer,
  );

  @protected
  FlutterCatalog sse_decode_flutter_catalog(SseDeserializer deserializer);

  @protected
  FlutterConnectionStats sse_decode_flutter_connection_stats(
    SseDeserializer deserializer,
  );

  @protected
  FlutterDecodedAudioFrame sse_decode_flutter_decoded_audio_frame(
    SseDeserializer deserializer,
  );

  @protected
  FlutterDecodedVideoFrame sse_decode_flutter_decoded_video_frame(
    SseDeserializer deserializer,
  );

  @protected
  FlutterDirectEvent sse_decode_flutter_direct_event(
    SseDeserializer deserializer,
  );

  @protected
  FlutterEncodedAudioFrame sse_decode_flutter_encoded_audio_frame(
    SseDeserializer deserializer,
  );

  @protected
  FlutterEncodedVideoFrame sse_decode_flutter_encoded_video_frame(
    SseDeserializer deserializer,
  );

  @protected
  FlutterEncoderPreset sse_decode_flutter_encoder_preset(
    SseDeserializer deserializer,
  );

  @protected
  FlutterFilterType sse_decode_flutter_filter_type(
    SseDeserializer deserializer,
  );

  @protected
  FlutterGroupOrder sse_decode_flutter_group_order(
    SseDeserializer deserializer,
  );

  @protected
  FlutterHardwareAccel sse_decode_flutter_hardware_accel(
    SseDeserializer deserializer,
  );

  @protected
  FlutterLiveEvent sse_decode_flutter_live_event(SseDeserializer deserializer);

  @protected
  FlutterMoqObject sse_decode_flutter_moq_object(SseDeserializer deserializer);

  @protected
  FlutterMoqStats sse_decode_flutter_moq_stats(SseDeserializer deserializer);

  @protected
  FlutterNamespaceAnnouncement sse_decode_flutter_namespace_announcement(
    SseDeserializer deserializer,
  );

  @protected
  FlutterObjectStatus sse_decode_flutter_object_status(
    SseDeserializer deserializer,
  );

  @protected
  FlutterPublisherStatus sse_decode_flutter_publisher_status(
    SseDeserializer deserializer,
  );

  @protected
  FlutterStreamEvent sse_decode_flutter_stream_event(
    SseDeserializer deserializer,
  );

  @protected
  FlutterSubscriberStatus sse_decode_flutter_subscriber_status(
    SseDeserializer deserializer,
  );

  @protected
  FlutterTicketInfo sse_decode_flutter_ticket_info(
    SseDeserializer deserializer,
  );

  @protected
  FlutterTrackInfo sse_decode_flutter_track_info(SseDeserializer deserializer);

  @protected
  FlutterTrackStatus sse_decode_flutter_track_status(
    SseDeserializer deserializer,
  );

  @protected
  FlutterTrackStatusCode sse_decode_flutter_track_status_code(
    SseDeserializer deserializer,
  );

  @protected
  FlutterVideoCodec sse_decode_flutter_video_codec(
    SseDeserializer deserializer,
  );

  @protected
  FlutterVideoFrame sse_decode_flutter_video_frame(
    SseDeserializer deserializer,
  );

  @protected
  FlutterVideoQuality sse_decode_flutter_video_quality(
    SseDeserializer deserializer,
  );

  @protected
  FlutterVideoQualityFfmpeg sse_decode_flutter_video_quality_ffmpeg(
    SseDeserializer deserializer,
  );

  @protected
  FlutterVideoRendition sse_decode_flutter_video_rendition(
    SseDeserializer deserializer,
  );

  @protected
  FlutterVideoTrack sse_decode_flutter_video_track(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_16(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<FlutterAudioRendition> sse_decode_list_flutter_audio_rendition(
    SseDeserializer deserializer,
  );

  @protected
  List<FlutterCaptureDevice> sse_decode_list_flutter_capture_device(
    SseDeserializer deserializer,
  );

  @protected
  List<FlutterDirectEvent> sse_decode_list_flutter_direct_event(
    SseDeserializer deserializer,
  );

  @protected
  List<FlutterEncodedVideoFrame> sse_decode_list_flutter_encoded_video_frame(
    SseDeserializer deserializer,
  );

  @protected
  List<FlutterLiveEvent> sse_decode_list_flutter_live_event(
    SseDeserializer deserializer,
  );

  @protected
  List<FlutterMoqObject> sse_decode_list_flutter_moq_object(
    SseDeserializer deserializer,
  );

  @protected
  List<FlutterNamespaceAnnouncement>
  sse_decode_list_flutter_namespace_announcement(SseDeserializer deserializer);

  @protected
  List<FlutterStreamEvent> sse_decode_list_flutter_stream_event(
    SseDeserializer deserializer,
  );

  @protected
  List<FlutterTrackInfo> sse_decode_list_flutter_track_info(
    SseDeserializer deserializer,
  );

  @protected
  List<FlutterVideoQuality> sse_decode_list_flutter_video_quality(
    SseDeserializer deserializer,
  );

  @protected
  List<FlutterVideoRendition> sse_decode_list_flutter_video_rendition(
    SseDeserializer deserializer,
  );

  @protected
  List<FlutterVideoTrack> sse_decode_list_flutter_video_track(
    SseDeserializer deserializer,
  );

  @protected
  List<int> sse_decode_list_prim_i_16_loose(SseDeserializer deserializer);

  @protected
  Int16List sse_decode_list_prim_i_16_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, bool)> sse_decode_list_record_string_bool(
    SseDeserializer deserializer,
  );

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  FlutterMoqObject? sse_decode_opt_box_autoadd_flutter_moq_object(
    SseDeserializer deserializer,
  );

  @protected
  FlutterNamespaceAnnouncement?
  sse_decode_opt_box_autoadd_flutter_namespace_announcement(
    SseDeserializer deserializer,
  );

  @protected
  FlutterPublisherStatus? sse_decode_opt_box_autoadd_flutter_publisher_status(
    SseDeserializer deserializer,
  );

  @protected
  FlutterSubscriberStatus? sse_decode_opt_box_autoadd_flutter_subscriber_status(
    SseDeserializer deserializer,
  );

  @protected
  FlutterTicketInfo? sse_decode_opt_box_autoadd_flutter_ticket_info(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_8(SseDeserializer deserializer);

  @protected
  Quality sse_decode_quality(SseDeserializer deserializer);

  @protected
  QualityConstraints sse_decode_quality_constraints(
    SseDeserializer deserializer,
  );

  @protected
  (String, bool) sse_decode_record_string_bool(SseDeserializer deserializer);

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  (int, int) sse_decode_record_u_32_u_32(SseDeserializer deserializer);

  @protected
  (int, int, int) sse_decode_record_u_8_u_8_u_8(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_Map_String_String_None(
    Map<String, String> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_String_bool_None(
    Map<String, bool> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_flutter_audio_samples(
    FlutterAudioSamples self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_flutter_broadcast_catalog(
    FlutterBroadcastCatalog self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_flutter_catalog(
    FlutterCatalog self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_flutter_connection_stats(
    FlutterConnectionStats self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_flutter_filter_type(
    FlutterFilterType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_flutter_moq_object(
    FlutterMoqObject self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_flutter_namespace_announcement(
    FlutterNamespaceAnnouncement self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_flutter_publisher_status(
    FlutterPublisherStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_flutter_subscriber_status(
    FlutterSubscriberStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_flutter_ticket_info(
    FlutterTicketInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_flutter_video_frame(
    FlutterVideoFrame self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_flutter_audio_codec(
    FlutterAudioCodec self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_flutter_audio_rendition(
    FlutterAudioRendition self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_flutter_audio_samples(
    FlutterAudioSamples self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_flutter_broadcast_catalog(
    FlutterBroadcastCatalog self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_flutter_capture_device(
    FlutterCaptureDevice self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_flutter_catalog(
    FlutterCatalog self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_flutter_connection_stats(
    FlutterConnectionStats self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_flutter_decoded_audio_frame(
    FlutterDecodedAudioFrame self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_flutter_decoded_video_frame(
    FlutterDecodedVideoFrame self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_flutter_direct_event(
    FlutterDirectEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_flutter_encoded_audio_frame(
    FlutterEncodedAudioFrame self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_flutter_encoded_video_frame(
    FlutterEncodedVideoFrame self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_flutter_encoder_preset(
    FlutterEncoderPreset self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_flutter_filter_type(
    FlutterFilterType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_flutter_group_order(
    FlutterGroupOrder self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_flutter_hardware_accel(
    FlutterHardwareAccel self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_flutter_live_event(
    FlutterLiveEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_flutter_moq_object(
    FlutterMoqObject self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_flutter_moq_stats(
    FlutterMoqStats self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_flutter_namespace_announcement(
    FlutterNamespaceAnnouncement self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_flutter_object_status(
    FlutterObjectStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_flutter_publisher_status(
    FlutterPublisherStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_flutter_stream_event(
    FlutterStreamEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_flutter_subscriber_status(
    FlutterSubscriberStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_flutter_ticket_info(
    FlutterTicketInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_flutter_track_info(
    FlutterTrackInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_flutter_track_status(
    FlutterTrackStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_flutter_track_status_code(
    FlutterTrackStatusCode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_flutter_video_codec(
    FlutterVideoCodec self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_flutter_video_frame(
    FlutterVideoFrame self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_flutter_video_quality(
    FlutterVideoQuality self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_flutter_video_quality_ffmpeg(
    FlutterVideoQualityFfmpeg self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_flutter_video_rendition(
    FlutterVideoRendition self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_flutter_video_track(
    FlutterVideoTrack self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_flutter_audio_rendition(
    List<FlutterAudioRendition> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_flutter_capture_device(
    List<FlutterCaptureDevice> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_flutter_direct_event(
    List<FlutterDirectEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_flutter_encoded_video_frame(
    List<FlutterEncodedVideoFrame> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_flutter_live_event(
    List<FlutterLiveEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_flutter_moq_object(
    List<FlutterMoqObject> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_flutter_namespace_announcement(
    List<FlutterNamespaceAnnouncement> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_flutter_stream_event(
    List<FlutterStreamEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_flutter_track_info(
    List<FlutterTrackInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_flutter_video_quality(
    List<FlutterVideoQuality> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_flutter_video_rendition(
    List<FlutterVideoRendition> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_flutter_video_track(
    List<FlutterVideoTrack> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_i_16_loose(
    List<int> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_i_16_strict(
    Int16List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_bool(
    List<(String, bool)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_flutter_moq_object(
    FlutterMoqObject? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_flutter_namespace_announcement(
    FlutterNamespaceAnnouncement? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_flutter_publisher_status(
    FlutterPublisherStatus? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_flutter_subscriber_status(
    FlutterSubscriberStatus? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_flutter_ticket_info(
    FlutterTicketInfo? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_8(int? self, SseSerializer serializer);

  @protected
  void sse_encode_quality(Quality self, SseSerializer serializer);

  @protected
  void sse_encode_quality_constraints(
    QualityConstraints self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_bool(
    (String, bool) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_u_32_u_32((int, int) self, SseSerializer serializer);

  @protected
  void sse_encode_record_u_8_u_8_u_8(
    (int, int, int) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
