// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'direct_flutter_api.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `get_direct_endpoint_holder`, `get_direct_event_queue`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`

/// Initialize the direct streaming endpoint
Future<String> initDirectStreaming() =>
    RustLib.instance.api.crateApiDirectFlutterApiInitDirectStreaming();

/// Get our endpoint ID for direct streaming
Future<String> getDirectEndpointId() =>
    RustLib.instance.api.crateApiDirectFlutterApiGetDirectEndpointId();

/// Create a direct stream as broadcaster and return the ticket
Future<String> createDirectStream({required String name}) =>
    RustLib.instance.api.crateApiDirectFlutterApiCreateDirectStream(name: name);

/// Join a direct stream as viewer
Future<String> joinDirectStream({
  required String ticketStr,
  required String name,
}) => RustLib.instance.api.crateApiDirectFlutterApiJoinDirectStream(
  ticketStr: ticketStr,
  name: name,
);

/// Send metadata (for broadcaster)
Future<void> directSendMetadata({
  required String fileName,
  required BigInt fileSize,
  required String mimeType,
  required int totalChunks,
  double? duration,
}) => RustLib.instance.api.crateApiDirectFlutterApiDirectSendMetadata(
  fileName: fileName,
  fileSize: fileSize,
  mimeType: mimeType,
  totalChunks: totalChunks,
  duration: duration,
);

/// Send a chunk (for broadcaster)
Future<void> directSendChunk({required int index, required List<int> data}) =>
    RustLib.instance.api.crateApiDirectFlutterApiDirectSendChunk(
      index: index,
      data: data,
    );

/// Request metadata (for viewer)
Future<void> directRequestMetadata() =>
    RustLib.instance.api.crateApiDirectFlutterApiDirectRequestMetadata();

/// Request a specific chunk (for viewer)
Future<void> directRequestChunk({required int index}) => RustLib.instance.api
    .crateApiDirectFlutterApiDirectRequestChunk(index: index);

/// Send presence (for keepalive)
Future<void> directSendPresence({required String name}) =>
    RustLib.instance.api.crateApiDirectFlutterApiDirectSendPresence(name: name);

/// Send arbitrary signal data
Future<void> directSendSignal({required List<int> data}) =>
    RustLib.instance.api.crateApiDirectFlutterApiDirectSendSignal(data: data);

/// Poll for direct stream events
Future<List<FlutterDirectEvent>> pollDirectEvents() =>
    RustLib.instance.api.crateApiDirectFlutterApiPollDirectEvents();

/// Get number of connected peers
Future<int> getDirectPeerCount() =>
    RustLib.instance.api.crateApiDirectFlutterApiGetDirectPeerCount();

/// Leave the direct stream
Future<void> leaveDirectStream() =>
    RustLib.instance.api.crateApiDirectFlutterApiLeaveDirectStream();

/// Shutdown direct streaming
Future<void> shutdownDirectStreaming() =>
    RustLib.instance.api.crateApiDirectFlutterApiShutdownDirectStreaming();

/// Check if direct streaming is initialized
bool isDirectStreamingInitialized() =>
    RustLib.instance.api.crateApiDirectFlutterApiIsDirectStreamingInitialized();

@freezed
sealed class FlutterDirectEvent with _$FlutterDirectEvent {
  const FlutterDirectEvent._();

  const factory FlutterDirectEvent.peerConnected({required String endpointId}) =
      FlutterDirectEvent_PeerConnected;
  const factory FlutterDirectEvent.peerDisconnected({
    required String endpointId,
  }) = FlutterDirectEvent_PeerDisconnected;
  const factory FlutterDirectEvent.requestMetadata({
    required String from,
    required BigInt timestamp,
  }) = FlutterDirectEvent_RequestMetadata;
  const factory FlutterDirectEvent.metadata({
    required String from,
    required String fileName,
    required BigInt fileSize,
    required String mimeType,
    required int totalChunks,
    double? duration,
    required BigInt timestamp,
  }) = FlutterDirectEvent_Metadata;
  const factory FlutterDirectEvent.requestChunk({
    required String from,
    required int index,
    required BigInt timestamp,
  }) = FlutterDirectEvent_RequestChunk;
  const factory FlutterDirectEvent.chunk({
    required String from,
    required int index,
    required Uint8List data,
    required BigInt timestamp,
  }) = FlutterDirectEvent_Chunk;
  const factory FlutterDirectEvent.presence({
    required String from,
    required String name,
    required BigInt timestamp,
  }) = FlutterDirectEvent_Presence;
  const factory FlutterDirectEvent.signal({
    required String from,
    required Uint8List data,
    required BigInt timestamp,
  }) = FlutterDirectEvent_Signal;
  const factory FlutterDirectEvent.error({required String message}) =
      FlutterDirectEvent_Error;
}
